Feature/ir 99/auth storage
pluraf/NanoNNG pull request #1
Opened 2024-08-12 15:37 UTC by gokceyetiserp

Added sqlite db for storing login credentials.

2024-08-12 20:11 UTC, konstaty requested changes

2024-08-12 20:11 UTC, konstaty commented on src/sp/protocol/mqtt/mqtt_parser.c
> +	createTable(db);
Why do you create DB every time you query for a auth record? (rhetorical question...)

2024-08-12 20:11 UTC, konstaty commented on src/sp/protocol/mqtt/mqtt_parser.c
> +			insertCredentials(db, auth_record.clientid, auth_record.auth_type, auth_record.username, auth_record.password);
The function ise called "**get**_auth_record" not **insert**_auth_method

2024-08-12 20:11 UTC, konstaty commented on src/sp/protocol/mqtt/mqtt_parser.c
>      if (strcmp(clientid, "client_pas") == 0) {
The whole if/else block checking for a specific client ids is not needed anymore, please delete it. It was used as a temporal stub while we didn't have a supprort for DB.

2024-08-13 08:37 UTC, gokceyetiserp commented on src/sp/protocol/mqtt/mqtt_parser.c
> +	createTable(db);
createTable function checks if db exists or not before creating, but i will change function.

2024-08-13 08:37 UTC, gokceyetiserp commented on src/sp/protocol/mqtt/mqtt_parser.c
> +			insertCredentials(db, auth_record.clientid, auth_record.auth_type, auth_record.username, auth_record.password);
Oh, I am sorry, I thought we will get credentials from client. I fixed it.

2024-08-13 12:54 UTC, closed without merging